// 初期
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//追記
import Link from 'next/link'
import Layout, { siteTitle } from './components/Layout'
import utilStyle from "../styles/utils.module.css"
import { Box, Button, Divider, Flex, Heading, Input, Stack } from "@chakra-ui/react";

// import {getPostsData} from "../lib/post";

// //SSGの場合
// export async function getStaticProps() {
//   const allPostsData = getPostsData(); // id,title,date,thumbnail
//   return {
//     props:{
//       allPostsData,
//     },
//   };
// }


// import { ChangeEvent, memo, useState, VFC } from "react";
import { useAuth } from "./hooks/useAuth";

import { PrimaryButton } from "./components/atoms/button/PrimaryButton";
import { useState } from 'react'
import { Header } from './components/Header'

// export default function Home( {allPostsData} ) {　引数があるときはこのコード
export default function Home() {
  const { login, loading } = useAuth();
  const [userId, setUserId] = useState("");
  const onChangeUserId = (e) =>
    setUserId(e.target.value);
  const onClickLogin = () => login(userId);

  return (
    <>
      {/* <Layout home> */}
      <Header></Header>
        <Head>
          <title>{siteTitle}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Flex align="center" justify="center" height="100vh">
          <Box bg="white" w="sm" p={4} borderRadius="md" shadow="md">
            <Heading as="h1" size="lg" textAlign="center">
              ユーザーログイン
            </Heading>
            <Divider my={4} />
            <Stack spacing={6} py={4} px={10}>
              <Input
                placeholder="ユーザーID"
                value={userId}
                onChange={onChangeUserId}
              />
              <PrimaryButton
                disabled={userId === ""}
                loading={loading}
                onClick={onClickLogin}
              >
                ログイン
              </PrimaryButton>
            </Stack>
          </Box>
        </Flex>
      {/* </Layout> */}
      </>
  )
}
