import React, { useState } from "react"
import { useRouter } from "next/router"
import Link from "next/link"

import { getAuth, createUserWithEmailAndPassword } from "firebase/auth"
import { useAuthContext } from "./AuthContext"
import { app } from "./firebase"
import { Box, Button, Divider, Flex, Heading, Input, Stack } from "@chakra-ui/react"
import Head from "next/head"
import { siteTitle } from './components/Layout'

const Signup = () => {
  const router = useRouter()
  const { user } = useAuthContext()
  const auth = getAuth(app)
  const isLoggedIn = !!user
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")

  const handleSubmit = async (e) => {
    e.preventDefault()
    await createUserWithEmailAndPassword(auth, email, password)
    router.push("/home")
  }
  const handleClose = async () => {
    await router.push("/")
  }
  const handleChangeEmail = (e) => {
    setEmail(e.currentTarget.value)
  }
  const handleChangePassword = (e) => {
    setPassword(e.currentTarget.value)
  }
  return (
    <div>
      {/* アラート機能を実装したい */}
                  {/* <Snackbar
        open={isLoggedIn}
        anchorOrigin={{ vertical: "top", horizontal: "center" }}
        autoHideDuration={3000}
        key={"top" + "center"}
        onClose={handleClose}
      >
        <Alert onClose={handleClose} severity="warning">
          すでにログインしています
        </Alert>
      </Snackbar> */}
            <form onSubmit={handleSubmit}>
        <Head>
          <title>{siteTitle}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Flex align="center" justify="center" height="100vh">
          <Box bg="white" w="sm" p={4} borderRadius="md" shadow="md">
            <Heading as="h1" size="lg" textAlign="center">
              ユーザー登録
            </Heading>
            <Divider my={4} />
            <Stack spacing={6} py={4} px={10}>
            <Input
              placeholder="メールアドレス"
              name="email"
              type="email"
              size="small"
              onChange={handleChangeEmail}
            />
            <Input
              placeholder="パスワード"
              name="password"
              type="password"
              size="small"
              onChange={handleChangePassword}
            />
              <Button
                bg="#506fb2"
                color="white"
                _hover={{ opacity: 0.8 }}
                disabled={email === "" || password === ""}
                type="submit" variant="outlined"
              >
                登録
              </Button>
              <div>
                <Link href={"/login"}>
                  <a>すでに登録している人はこちら</a>
                </Link>
              </div>
            </Stack>
          </Box>
        </Flex>
      </form>
    </div>
  )
}

export default Signup